; Engine ids: `camera::forward`, `camera::back`, `character::forward` e.t.c.

[camera]
forward = W
back = S
left = A
right = D
up = E
down = Q

[character]
forward = RIGHT
back = LEFT
up = UP
down = DOWN
